version: "3.7"
services: 
    api:
        build: './api'
        container_name: api
        volumes: 
            - ./api:/api/app/
            - /api/app/node_modules
        ports:
            - 5000:5000
    web:
        stdin_open: true
        tty: true
        build: './web'
        container_name: web
        volumes:
          - ./web:/web/app/
          - /web/app/node_modules
        ports:
          - 3000:3000
        environment:
          - CHOKIDAR_USEPOLLING=true