version: "3"
services: 
    api:
        container_name: api
        build: './api'
        command: npm start
        volumes: 
            - .:/app
            - /app/node_modules
        ports:
            - "5000:5000"
    client:
        container_name: client
        tty: true
        build: './web'
        volumes:
          - '.:/app'
          - '/app/node_modules'
        ports:
          - 3000:3000
        environment:
          - CHOKIDAR_USEPOLLING=true